### ISSUE TITLE
Guzzle didn't work in prod because required only in dev

### ISSUE THREAD

**Issue by r3bers** [codenix-sv/bittrex-api#5]
This one:
https://github.com/codenix-sv/bittrex-api/blob/c4499011e6b2cbd831734f23aa68f79ddfa0e698/composer.json#L26
Better Be in this section:
https://github.com/codenix-sv/bittrex-api/blob/c4499011e6b2cbd831734f23aa68f79ddfa0e698/composer.json#L19
Not this one: 
https://github.com/codenix-sv/bittrex-api/blob/c4499011e6b2cbd831734f23aa68f79ddfa0e698/composer.json#L24

**Comment by codenix-sv** [comment]
Thank you for your feedback! Fixed
